package org.dashbuilder.displayer;

public enum DisplayerSettingId {

    TYPE,
    RENDERER,
    COLUMNS,

    TITLE,
    TITLE_VISIBLE,
    FILTER_ENABLED,
    FILTER_SELFAPPLY_ENABLED,
    FILTER_NOTIFICATION_ENABLED,
    FILTER_LISTENING_ENABLED,

    CHART_WIDTH,
    CHART_HEIGHT,
    CHART_MARGIN_TOP,
    CHART_MARGIN_BOTTOM,
    CHART_MARGIN_LEFT,
    CHART_MARGIN_RIGHT,
    CHART_SHOWLEGEND,
    CHART_LEGENDPOSITION,
    CHART_3D,

    TABLE_PAGESIZE,
    TABLE_WIDTH,
    TABLE_SORTENABLED,
    TABLE_SORTCOLUMNID,
    TABLE_SORTORDER,

// TODO all the following are yet to be applied to their respective displayers
    XAXIS_SHOWLABELS,
    XAXIS_LABELSANGLE,
    XAXIS_TITLE,
    YAXIS_SHOWLABELS,
    YAXIS_LABELSANGLE,
    YAXIS_TITLE,

    METER_START,
    METER_WARNING,
    METER_CRITICAL,
    METER_END,

    BARCHART_HORIZONTAL;

}
